# cilium-bgp-peering-policies.yaml 
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium01
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cilium-srv6-lab-cluster01-control-plane
  virtualRouters:
  - localASN: 65001
    exportPodCIDR: true
    mapSRv6VRFs: true
    neighbors:
    - peerAddress: "fd00:172:100:100::1/128"
      peerASN: 65000
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 180
      keepAliveTimeSeconds: 60
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      families:
       - {afi: "ipv4", safi: "mpls_vpn"}
       - {afi: "ipv6", safi: "mpls_vpn"}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium02
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cilium-srv6-lab-cluster02-control-plane
  virtualRouters:
  - localASN: 65002
    exportPodCIDR: true
    mapSRv6VRFs: true
    neighbors:
    - peerAddress: "fd00:172:200:200::1/128"
      peerASN: 65000
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 180
      keepAliveTimeSeconds: 60
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      families:
       - {afi: "ipv4", safi: "mpls_vpn"}
       - {afi: "ipv6", safi: "mpls_vpn"}