# cilium-bgp-peering-policies.yaml 
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium01
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cilium-srv6-lab-cluster01-control-plane
  virtualRouters:
  - localASN: 65001
    srv6LocatorPoolSelector:
        matchLabels:
          export: "true"
    neighbors:
    # Advertises a locator prefix to the underlay network with eBGP
    - peerASN: 65000
      peerAddress: "fd00:172:100:100::1/128"
      families:
       - {afi: "ipv6", safi: "unicast"}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium02
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cilium-srv6-lab-cluster02-control-plane
  virtualRouters:
  - localASN: 65002
    srv6LocatorPoolSelector:
        matchLabels:
          export: "true"
    neighbors:
    # Advertises a locator prefix to the underlay network with eBGP
    neighbors:
    - peerAddress: "fd00:172:200:200::1/128"
      peerASN: 65000
      families:
       - {afi: "ipv6", safi: "unicast"}