# Cilium enterprise values
hubble:
  enabled: true
  relay:
    enabled: false
debug:
  enabled: true
ipv6:
  enabled: true
enterprise:
  srv6:
    enabled: true
    encapMode: reduced
    locatorPoolEnabled: true
bgpControlPlane:
  enabled: true
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true
ipam:
  mode: kubernetes
tunnel: disabled
ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6NativeRoutingCIDR: 2001::/16
