# cluster01.yaml
kind: Cluster
name: cilium-srv6-lab-cluster01
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  disableDefaultCNI: true 
  podSubnet: 10.1.0.0/16,2001:dead:10:0::/63
  serviceSubnet: 10.111.0.0/16,2001:beaf:1::/108
nodes:
- role: control-plane
  image: nicolaka/netshoot:latest
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: "172.100.100.2,fd00:172:100:100::2"
        node-labels: "vrf=vrf01"
#BGP local peer address
- role: worker
  image: nicolaka/netshoot:latest
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: "10.1.1.1,2001:dead:10:1:1::1"
        node-labels: "vrf=vrf01"
