# cluster01.yaml
kind: Cluster
name: kubernetes-cluster01
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  disableDefaultCNI: true 
  podSubnet: 10.1.0.0/16,2001:db8:10:0::/56
nodes:
- role: control-plane
  
- role: worker
  
- role: worker