# cluster02.yaml
kind: Cluster
name: kubernetes-cluster02
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  disableDefaultCNI: true 
  podSubnet: 10.2.0.0/16,2001:db8:20:0::/56
  serviceSubnet: 10.222.0.0/16
nodes:
- role: control-plane
  
- role: worker